apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  labels:
    app: app
    tier: backend
    track:  latest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appgit remote -v

      tier: backend
      track: latest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
        tier: backend
        track: latest
    spec:
      containers:
        - image: (ommite)
          imagePullPolicy: IfNotPresent
                    resources: {}
          ports:
            - name: http
              containerPort: 80e